<a href="https://colab.research.google.com/github/nurimammasri/Wooky-Numpy/blob/main/%5BAddition%5D%20NumPy%2001%20Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Libraries - NumPy
---

# Table Of Content

- [Installation](##Installation)
- [Introduction](#NumPy:-Numeric-computing-library)
    - What is numpy
    - Performance comparison with Python list
- [Numpy Array](#Numpy-Arrays)
    - Creating numpy array from list
    - Creating numpy array with built-in methods
- [Array Attributes and Methods](#Array-Attributes-and-Methods)
- [Dimensions and Shapes](#Dimensions-and-Shapes)

## Installation

* **Through Anaconda Naviagtor**

* **Through conda prompt**
    * **Conda Install**
            >>conda install <libName/pkgName>
    * **Pip Install**
            >>python -m pip install jupyter_contrib_nbextensions --user
            >>jupyter contrib nbextension install --user
            >>jupyter nbextension enable varInspector/main

            >>pip install SomePackage==1.0.4    # specific version

### Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

In [1]:
#!pip install --user --upgrade pixiedust
#import pix## Installation Instructions

---
<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# NumPy: Numeric computing library

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also **incredibly fast**, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

[Back to top](#Table-Of-Content)

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
#Purpose of program
import numpy as np
import pandas as pd

## List and Array Performance Comparison

Before we jump in, let's check list and array computation time

In [3]:
l = list(range(100000))

In [4]:
a = np.arange(100000)

In [5]:
%time np.sum(a ** 2)

CPU times: user 538 µs, sys: 926 µs, total: 1.46 ms
Wall time: 5.49 ms


333328333350000

In [6]:
%time sum([x ** 2 for x in l])

CPU times: user 36.5 ms, sys: 4.37 ms, total: 40.8 ms
Wall time: 42.2 ms


333328333350000

---
Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

[Back to top](#Table-Of-Content)

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [7]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [8]:
np.array(my_list)

array([1, 2, 3])

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
my_matrix*2

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.array(my_matrix)*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

### `dtype`

Data Types in Python
By default Python have these data types:

* strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
* integer - used to represent integer numbers. e.g. -1, -2, -3
* float - used to represent real numbers. e.g. 1.2, 42.42
* boolean - used to represent True or False.
* complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string
* V - fixed chunk of memory for other type ( void )

You can also grab the data type of the object in the array:

In [13]:
np.array(my_matrix).dtype

dtype('int64')

### Built-in Methods

There are lots of built-in ways to generate Arrays

### `arange`

Return evenly spaced values within a given interval.

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### `zeros` and `ones`

Generate arrays of zeros or ones

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones(3)

array([1., 1., 1.])

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### `linspace`
Return evenly spaced numbers over a specified interval.

In [20]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

## `eye`

Creates an identity matrix

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### `rand`
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1]``.

In [23]:
np.random.rand(2)

array([0.07272433, 0.79216679])

In [24]:
np.random.rand(5,5)

array([[0.54572929, 0.53629384, 0.37511398, 0.54133327, 0.89020261],
       [0.91582025, 0.28129232, 0.706866  , 0.06522363, 0.66038909],
       [0.04742013, 0.54208464, 0.56225522, 0.36264356, 0.89467464],
       [0.81299039, 0.46023776, 0.9734279 , 0.98704511, 0.55260992],
       [0.80448295, 0.80536231, 0.24718134, 0.0030294 , 0.81131345]])

### `randn`

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [25]:
np.random.randn(2)

array([-0.81699469,  1.96272431])

In [26]:
np.random.randn(5,5)

array([[ 0.41705375, -0.70263369, -2.5296108 ,  0.68577945,  0.96001264],
       [-0.96988654, -1.8447626 ,  0.50968453, -1.56254033,  1.0086461 ],
       [ 1.24675028,  0.79696456, -0.62654136, -0.30512687,  0.15651383],
       [ 2.06564185,  0.4186536 , -0.28038946,  1.74420042,  0.04246886],
       [ 0.00428248, -0.37077574, -0.54271966, -0.45187693,  1.73003009]])

### `randint`
Return random integers from `low` (inclusive) to `high` (exclusive).

In [27]:
np.random.randint(1,100)

16

In [28]:
np.random.randint(1,100,10)

array([97, 92, 36, 99, 95, 28, 14, 82,  9, 73])

# QnA

---
# Array Attributes and Methods

Let's discuss some useful attributes and methods or an array

[Back to top](#Table-Of-Content)

In [29]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr

array([ 4, 28, 33, 19, 46, 42, 15, 29, 40, 18])

### `reshape`
Returns an array containing the same data with a new shape.

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### `max`, `min`, `argmax`, `argmin`

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [33]:
ranarr

array([ 4, 28, 33, 19, 46, 42, 15, 29, 40, 18])

In [34]:
ranarr.max()

46

In [35]:
ranarr.argmax()

4

In [36]:
ranarr.min()

4

In [37]:
ranarr.argmin()

0

---
# Dimensions and Shapes

## `ndim`, `size`, and `shape`

- Shape is an attribute that arrays have (not a method)
- `ndim` returns the array dimension
- `size` returns the number of elements in the array

[Back to top](#Table-Of-Content)

In [38]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [39]:
A.shape

(2, 3)

In [40]:
A.ndim

2

In [41]:
A.size

6

In [42]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [43]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [44]:
B.shape

(2, 2, 3)

In [45]:
B.ndim

3

In [46]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [47]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  import sys


In [48]:
C.dtype

dtype('O')

In [49]:
C.shape

(2,)

In [50]:
C.size

2

In [51]:
type(C[0])

list